# Generated by Django 2.0.6 on 2020-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_user', '0009_auto_20190228_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationrecord',
            name='ldap_email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
